version: '3.9'
services:
  tarifarito_app_container:
    container_name: tarifarito_app_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/Bogota
      FLASK_APP: "app"
      FLASK_ENV: "development"
      TOOL_KEY: "U2FsdGVkX19ooBjsgDGiIDvNsbUndXRCVx32+kvjbP0ygyMHkaQJs4VTrypDob2g0BOyjd8KO10Z1OP4EKk+GQ=="
    volumes:
      - ./Backend:/app/
    ports:
      - "5063:5063"
    depends_on:
      - tarifarito_pg_container
      - tarifarito_mongo_db_container
    networks:
      #- gestordeaplicaciones-api_gestor-network
      - tarifarito-network

  tarifarito_pg_container:
    container_name: tarifarito_pg_container
    image: postgres
    restart: always
    environment:
      TZ: America/Bogota
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: S5a06ELZAxvNxQ6aVOkfycU2db5hA4
      POSTGRES_DB: gestor_aplicaciones
    expose:
      - '5432:5432'
    volumes:
      - tarifarito-db:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/procesos_dieg.sql:/docker-entrypoint-initdb.d/procesos_dieg.sql
    networks:
      #- gestordeaplicaciones-api_gestor-network
      - tarifarito-network

  tarifarito_mongo_db_container:
    container_name: tarifarito_mongo_db_container
    image: mongo:4.2
    restart: always
    environment:
      TZ: America/Bogota
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_DATABASE: tarifarito
      MONGO_INITDB_ROOT_PASSWORD: XM6IgfHVcMUxyR7dfw4e
    expose:
      - '27017:27017'
    volumes: 
      - tarifarito-mongo-db:/data/db
    networks:
      - tarifarito-network

  tarifarito_mongo_express_container:
      container_name: tarifarito_mongo_express_container
      image: mongo-express
      restart: always
      ports:
        - "8081:8081"
      depends_on:
        - tarifarito_mongo_db_container
      environment:
        TZ: America/Bogota
        ME_CONFIG_MONGODB_SERVER: tarifarito_mongo_db_container
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: XM6IgfHVcMUxyR7dfw4e
        ME_CONFIG_BASICAUTH_USERNAME: admin@admin.com
        ME_CONFIG_BASICAUTH_PASSWORD: 123456789
      volumes: 
        - tarifarito-mongo-db:/data/db
      networks:
        - tarifarito-network

  tarifarito_pgadmin4_container:
    container_name: gestor_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      TZ: America/Bogota
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    ports:
      - "8082:80"
    volumes:
      - tarifarito-db:/var/lib/postgresql/data
    networks:
      - tarifarito-network

volumes:
  tarifarito-db:
  tarifarito-mongo-db:

networks:
  tarifarito-network:
  #gestordeaplicaciones-api_gestor-network:
    #external: true
