import os

DEBUG = True
PUBLIC = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = 'oracle://JHERRERAA:C0l0mb1a_2020@172.16.1.185:2230/DBSUI' # BD SUI
CONNECTION_STRING_MONGODB = 'mongodb://localhost:27017'
BD_MONGODB = 'tarifarito'
